### ISSUE TITLE
Tracing - Debug Enhancement Inputs

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#11]
Hi Tom, 

You mentioned working on Debug so I thought I should share a few thoughts that came to mind to me while using the tools.   Feel free to just close issue right away. 

I am only sharing a few passing thoughts.

1.  So many things classified as an Error was hard to find true system errors.  Like where business rule enforcement is classified as an error (one example:  pre-validation checks where entry Long denied because you are already Long).   

I was thinking .. just ideas to share:
It would be nice to in a more easy fashion find the true system errors 
It would be easier to leverage the debugging for both coding and Algo design and validation if some of the categories tagged as error now where instead labeled EntryRule (like any pre-validation failure), ExitRule and ChangeRule.   Now I can use the debugging kit to help me ongoing basis track, manage and improve Algo logic.  

2. You did a really nice consistent job of writing in the trace details through the whole app.  Right away in order to easily and quickly reduce/filter all that great content to just the most pressing issues of the day.  There are many ways to filter output and they are all good.   

The lazy method I personally keep going back to is this silly simple little Int var DynamicLimiter combined with the on/off print bool.  It is so easy just to edit the number while you are right looking at the code block.   In this case errors over 20 always print or hit the log and I can adjust up a thread through the workflow to 15 so I can chase a problem and drop quickly drop them back down  when the issue is closed.  

if(PrintDetailsAlgoLogic)  if(PrintDetailsDynamicLimiter > 7)

Just passing on a simple ideas expecting I might stir yet better ideas from you.

**Comment by jmscraig** [comment]
I see you committed.  I will pull that down and have a look.

**Comment by MicroTrendsTom** [comment]
i think for AlgoRules that could be a level above and an override of the base one for the engine to keep them seperate  -perhaps even wruite rules to a different trace file or mix it in   -  so yes agreed a kind of trace switch also 

but what of autoflush?

**Comment by jmscraig** [comment]
"but what of autoflush?"  

Can you describe a little about what you mean by autoflush.. a FlattenAll ?

**Comment by MicroTrendsTom** [comment]
Trace.Autoflush
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.trace.autoflush?view=net-5.0
I believe we write  and flush each  time and so we don't miss any messages or atleast not too many in result of a crash out



________________________________

**Comment by jmscraig** [comment]
Thanks.

Question:  Would you prefer Issues tagged 'Documentation' to have broad discussion content or  thinner just to propose cleanup edits to content in the first post.?

**Comment by MicroTrendsTom** [comment]
yes i think more focused specific to one subject within a subject or broader one for easy following and close/archive
