### ISSUE TITLE
System test  mode

### ISSUE THREAD

**Issue by MicroTrendsTom** [MicroTrendsLtd/NinjaTrader8#13]
Add in a System Test mode so we can set on  a Zsytem Public param " System Test Mode"  on that throws curve balls into the trading flow.. such as addiitonal orders. rejects and any other item you can think of   -this will work of OnMarketUpdate and should randomly try to trip over the engine and force errors etc  

prove
#1 deadlocks are gone
#2 fault tolerance and recovery

**Comment by jmscraig** [comment]
Excellent
