### ISSUE TITLE
fast market cancel pending - stuck orders how to remove them

### ISSUE THREAD

**Issue by MicroTrendsTom** [MicroTrendsLtd/NinjaTrader8#15]
fast market cancel pending - stuck orders how to remove them.
Its possible to get pesky stuck orders... which did not return in a callback to move on....
NT8 makes no effort to deal with these...

there are 2 in this screen shot
![image](https://user-images.githubusercontent.com/24366913/101043110-f12cda80-354b-11eb-9cc1-4294c26f234d.png)

Super renko 2 tick at the NQ open  -obviously untradeable - but simply a soak test.  produced 2 stuck orders on chart
![image](https://user-images.githubusercontent.com/24366913/101043213-102b6c80-354c-11eb-96b0-08041e1c3383.png)

So to deal with these...
#1 to remove from realtime view
#2 to remove from the DB so they are gone without an account reset

#2 is easist in fact..

**Comment by jmscraig** [comment]
"#2 is easist in fact.." 
Agreed.  

My "lets not play around and get something done" aggressive soak testing" adds about 100MB to the NT8 db per day and sometimes 2-10 hung orders.

How many hours to you need to give up your machine to do a reset on that DB each day?

Dont know, cant give up the hours of machine time for reset so just delete it and replace. 

I have decided that when I have time I will create a very small version of the db I like with trading hours templates I use etc and then copy it to a changed name as a ready Archived version.

When just heavy testing will take place copy the real db to a temp holding name and copy test version db Archive in to be used as the db during testing.   At end of test delete the 120MB db and copy back the production version

**Comment by jmscraig** [comment]
When orders hang in a 'throw away' testing sim account db I just add another sim account to that db to test against to hung orders can be sure to not impact testing

**Comment by MicroTrendsTom** [comment]
Yep agreed,. i got some code that monitors for Stuck orders and deals with them from within an AddOn class
