### ISSUE TITLE
Improve NT8 Reliability by Auto-Closing WPF Popup Windows

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#19]
Hi Tom, 

 I would tag this "Enhancement"

NT8 uses the Microsoft WPF libraries for UI construction.

NT8's implementation of Popups via WPF adds significant unreliability leaving "lights out" operation capability at risk.   
1) The launch of Popup windows by NT8 within milliseconds of other Windows receiving focus leaves them blocked behind out of sight and inaccessible for acknowledgement and closure. 
2) The stacking of many 'Order Rejected"  WPF Popup windows soon begins to degrade NT8 reliability.

ENHANCEMENT in response:  Automatically Identify and close NT8's Popup windows soon after they are launched.

Below is a thread on the NT forums that discuss and path to resolution

---------------

https://ninjatrader.com/support/forum/forum/ninjatrader-8/strategy-development/1052909-realtimeerrorhandling-ignoreallerrors
'

ControlCenter cc = NinjaTrader.Core.Globals.AllWindows.First(t => t is ControlCenter) as ControlCenter;
if (cc != null)
{
    cc.Dispatcher.InvokeAsync(() =>
    {
        System.Windows.Controls.Button closeButton = cc.FindFirst("NTWindowButtonClose") as System.Windows.Controls.Button;
        if (closeButton != null) {
            System.Windows.Automation.Peers.ButtonAutomationPeer peer = new System.Windows.Automation.Peers.ButtonAutomationPeer(closeButton);
            System.Windows.Automation.Provider.IInvokeProvider invokeProv = peer.GetPattern(System.Windows.Automation.Peers.PatternInterface.Invoke) as System.Windows.Automation.Provider.IInvokeProvider;
            if (invokeProv != null) invokeProv.Invoke();
        }
    });
}

cancleOrdersSentNoticeEndTime

 if (DateTime.Now > a.ActionDateTime.AddSeconds(TradeSignalExpiryInterval))
                {

            if (AlgoSignalAction == AlgoSignalAction.None)
            {
                //belt and braces check
                if (State != State.Historical && TradeWorkFlow == StrategyTradeWorkFlowState.ErrorFlattenAll 
			&& TradeWorkFlowLastChanged < DateTime.Now.AddSeconds(3))
                    ProcessWorkFlow();

                return;
            }

 if (DateTime.Now < onMarketDataTimeNextAllowed) return;
            onMarketDataTimeNextAllowed = DateTime.Now.AddSeconds(1);

private DateTime flattenOrCancelOrdersInitiatedNoticeEndTime;

// two lines below added because OnOrderUpdate() refresh is not fast enough to prevent orders in error. Notice is reset at top of OnMarketData().
			bFlattenOrCancelOrdersInitiated = true;
			flattenOrCancelOrdersInitiatedNoticeEndTime = DateTime.Now.AddMilliseconds(2500);

            if (marketDataUpdate.MarketDataType == MarketDataType.Bid || marketDataUpdate.MarketDataType == MarketDataType.Ask)
            {
                if (DateTime.Now < onMarketDataBidTimeNextAllowed) return;
                onMarketDataBidTimeNextAllowed = DateTime.Now.AddMilliseconds(250);
                AskPrice = marketDataUpdate.Ask;
                BidPrice = marketDataUpdate.Bid;
                return;
            }

'

**Comment by MicroTrendsTom** [comment]
hahaha love it - this has been  on my to do list for EONS.. .especically at startup we dont want some inane message to prevent the startup or millions of popups... very good... in fact i found popups caused lockups...~!

**Comment by MicroTrendsTom** [comment]
NT were planning a simple window grid with messages to prevent this craziness!!!! but that has not appeared yet  -which undermines the whole enterprise as does the mutant dinosaur database technology -sadly not replaced by a proper dev MSSQL for NT9 end of rant...
