### ISSUE TITLE
How to enable BackTest and Optimization through the Strategy Analyzer?

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#2]
Greetings, 

I noticed logic built into AlgoSystemsBase.cs to handle Backtest execution.  

When attached directly as a strategy to a chart the included sample generates an expected large number of historical trades.

Strategy Analyzer executes Backtest and Optimization processes on the sample but produces no trades.  

Any tips on how to get this sample working well with the Strategy Analyzer?

Thanks!

**Comment by MicroTrendsTom** [comment]
hi

thanks for the info - i would have to test this to replicate as far as i was aware it would work the same if it cold work on a chart etc

**Comment by MicroTrendsTom** [comment]
so if i'm right this was due to error corrected in your modification OnStateChange, So we can close this one?

**Comment by jmscraig** [comment]
Hi Tom, Thanks for the reply.  

No I still have not been able to get any results to appear via the Strategy Analyzer via BackTest or Optimization modes.

On the upside I am testing out a few possible suggested changes to reduce rejected change orders on fast moving tick charts

**Comment by MicroTrendsTom** [comment]
ok perfect i am going to deal with this one now

**Comment by MicroTrendsTom** [comment]
"On the upside I am testing out a few possible suggested changes to reduce rejected change orders on fast moving tick charts"
Sounds interesting.  
I did add an Unsafe mode -- to cut out all the workflow - but it lacks a post trade - context check to make sure the entry's and exits are in balance etc

**Comment by MicroTrendsTom** [comment]
ok latest version fixed an erroneous property IsReplay OnBarUpdate - which tested for replay account 
also optimised code execution for backtest and also for Realtime in release notes etc
