### ISSUE TITLE
Simulated OCA

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#20]
NOTICE: Only recommended for short lived trades (or could be short lived and trade management plan might be updated later) under strong multi-geography response action oriented over-watch risk management controls.

MOVTIVATION: OCO adds rule constraints and significant timing delays.

Add capability to execute and manage trades via OCA.

**Comment by MicroTrendsTom** [comment]
ok can delete we can talk at tom@microtrends.pro also
