### ISSUE TITLE
Test Report - 2020-12-08

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#24]
Morning.  

I see you made a good size commit with lots of changes so these test results are not reflective of the current code.

Ran four clients overnight, all unmodified code.  2 PriceReversal, to MACrossover 

All four visually appear to be still running but charts on the VPS are stuck at 12:45am on the Dev machine they are both stuck at 12:47am.  

Overnight the VPS had no other strategies or charts running.

All other charts on the Dev machine (18 charts heavily loaded with indicators and a some strategies) ran perfectly and are showing correct times.  

I will pull down the commits and put that up for a test.

![image](https://user-images.githubusercontent.com/15313578/101502842-0e401f80-3937-11eb-8dba-08c2ca108b1d.png)

Config of PriceReversal

![image](https://user-images.githubusercontent.com/15313578/101503059-53fce800-3937-11eb-8e75-16c78405f68f.png)

Config of the MACrossover
![image](https://user-images.githubusercontent.com/15313578/101503240-827ac300-3937-11eb-841a-04cecc7840c6.png)

**Comment by MicroTrendsTom** [comment]
Awesome.... :-)

**Comment by jmscraig** [comment]
> for simple fast actions where there was not enumeration of a list with a possible change etc.

In debug did you see any locking up?


> may indeed work better off chart as an invisible strategy 

I agree that thus far environmental factors seem to influence the reliability.
Usually, strategies with lots of tracing enabled have been more reliable than when running without.  

So much that it left me thinking..  
- if it is reliable on an 8 tick with tracing maybe it will still be reliable on a 12 tick but for sure a 20tick.
- we can trade consider both tracing and configured cycle times as being a combined buffering solution.

**Comment by jmscraig** [comment]
From all the reading multiple threads even reading the same list with "contains" or even a .ToArray() call is like buying a lottery ticket.. best case it will happen rarely but eventual some hits 

Long term I will not be surprised to see a ConcurrentDictionary replace the use of Lists.

**Comment by jmscraig** [comment]
90 mins into this test ..  
PriceReversal 1 second and 2 secnod running great.   100% default configs.
MACross MNQ 18tick Hung and frooze the chart in 15 min (no logging or tracing enabled).
MACross MNQ 8tick is running great(no logging or tracing enabled).

**Comment by jmscraig** [comment]
fyi .. .example use of ConcurrentDictionary in OnMarketData()

'

uint ui_volume ;
lock (e.Instrument.SyncMarketData)
{
        ui_volume = (uint)e.Volume ;
        _cdictionary.AddOrUpdate(e.Price, ui_volume, (price, oldVolume) => oldVolume + ui_volume);
}

'

**Comment by jmscraig** [comment]
NT Jim posted a good example use of Concurrent dictionary more complex than replacing the lists..  Using a data Class to add multiple items per dictionary row. 

https://ninjatrader.com/support/forum/forum/ninjatrader-8/strategy-development/102909-imbalance-strategy?p=803902#post803902

That slows things down a lot and generates a lot heap GC pressure so not encouraged unless  really needed but proves the ConDict is viable for far more than is needed here.

ConcurrentDictionaries 200-400% slower to load each row than a list, but provide lock like security for read with no identifiable locks or locking if your the reader. 

We read so much more than we write so the ConDict might be a massive win.

**Comment by jmscraig** [comment]
just replacing the list looks much simpler than NT Jim's example..  

much more like example from dotnetpearls

`
using System;
using System.Collections.Concurrent;

class Program
{
    static void Main()
    {
        // New instance.
        var con = new ConcurrentDictionary<string, int>();
        con.TryAdd("cat", 1);
        con.TryAdd("dog", 2);

        // Try to update if value is 4 (this fails).
        con.TryUpdate("cat", 200, 4);

        // Try to update if value is 1 (this works).
        con.TryUpdate("cat", 100, 1);

        // Write new value.
        Console.WriteLine(con["cat"]);
    }
}
`

**Comment by jmscraig** [comment]
The majority of content in this issue no longer top shelf relevant so closing
