### ISSUE TITLE
Test Report 2020-12-08 - #2  

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#28]
90 mins into this test ..
PriceReversal 1 second and 2 secnod running great. 100% default configs.
MACross MNQ 18tick Hung and frooze the chart in 15 min (no logging or tracing enabled).
MACross MNQ 8tick is running great(no logging or tracing enabled).

---------------------------------------------------------------------------------

3 hours in, now both MACross clients have Hung / Frozen.   (no logging or tracing enabled).  

Switching logging to the MACross client.

**Comment by MicroTrendsTom** [comment]
What settings for the MACross client?  i guess its latest v etc?

**Comment by MicroTrendsTom** [comment]
> Switching logging to the MACross client.

VS Debubbing with output window on will show the full gamut of methods and events up to the lock not seen in trace
plus trace interweaved
Also then if a lock has occurred you can click pause and see where it was etc   -  for this reason i test 1 strategy per server for that

**Comment by jmscraig** [comment]
Hi Tom, just logging off to go to bed. 

> What is the config

Given the rapid recent changes I am typing to stay with the exact defaults you are submitting the strategies with... at least for the first rounds of testing. 

This is config is currently running with an intent for strong tracing to help debug any issues that surface.  Any recommended changes?

Night!

![image](https://user-images.githubusercontent.com/15313578/101589018-3bc7b000-39ad-11eb-9011-0789cc4226f5.png)

**Comment by MicroTrendsTom** [comment]
ok i will need to also test this and debug to try replicate the messages -  i dont seem to get more than 1 or 2 after running all through the session etc on too fast settings to provoke issues.. 
I will setup a test also
What is the dataseries for that?

**Comment by jmscraig** [comment]
This morning Test Reportout:

MACross crashed at 9:06am with one Sell Stop order hung, un-cancelable in the Sim account.

The last few popups all said something like "Unable to verify ErrorFlattenAllConfirmed"

Next round will enable full tracing, it was not on.  

Log shows repeated rounds of "Unable to verify ErrorFlattenAllConfirmed".
Two different message strings (e.g. likely sent from at least two diff locations )

183 instances of the same error message starting when the market go faster at 8:31am.

I have seen this messaging as a precursor to hang consistantly in all MACross/AlgoSystemBase version combinations.




![image](https://user-images.githubusercontent.com/15313578/101660795-313d0300-3a0d-11eb-948f-0d57d29c355e.png)

**Comment by jmscraig** [comment]
> ... more on ... is this from timing delays from Sim system processing errors?

Re-writing this line "is this from timing delays from (or related to) Sim system processing errors?" 

Over the whole night:

* At 6:58am there were to rejected orders via "Cancel Pending" status. These did not produce or were not near any visible errors from the system.

* At 8:33 am there were four rejections due to Sell stop or sell stop limit orders (most likely ChangeOrder() ) can't be placed above the market.'    These are likely to system lag or data lag at the open. (will add a 1 tick BarArray) to for order execution to reduce the risk of the "Above the Market' error.
* The first of many ErrorFlattenAllConfirmed errors started at 8:31.  Could be related to the Sim processing errors, but at that time of day system slow down might alone be the breaking point. 

![image](https://user-images.githubusercontent.com/15313578/101666231-8ed44e00-3a13-11eb-9a5b-3f735a649f66.png)

**Comment by jmscraig** [comment]
Next test is on the latest commit

**Comment by MicroTrendsTom** [comment]
Ok
So the Error workflow has started and cannot close or cancel or confirm it has been closed/flattened
So it keeps trying then when its resetting state - it does another attempt of a different nature on all "Orders"
Ok this would be great to replicate so i can see why it tries and tries againg when that never happens on any machine i have or strategy what is diferrent etc

What DataSeries are you using?
I can get the settings from the above

**Comment by jmscraig** [comment]
I think this time (though it happened afterhours as well) I think it is most likely related to the heavy processing load at the open.  

18tick.. now running a 1 second which is more like 24-40tick

**Comment by MicroTrendsTom** [comment]
The part in question is

look from 
case StrategyTradeWorkFlowState.Error:
to
case StrategyTradeWorkFlowState.ErrorFlattenAllPending:

what part can it not deal with...
if (Position.MarketPosition == MarketPosition.Flat)

that ends in a friendly Flatten to keep it all alive etc  as a Position.Close or  Account.Flatten(new[] { Instrument });  would halt it etc

**Comment by jmscraig** [comment]
>  we need to see the trace log to see the issue
looks like Default properties did not have trace turned on so enabling workflow trace

traceorder did not add any value this round so disabling that for this test.

**Comment by jmscraig** [comment]
> that ends in a friendly Flatten to keep it all alive etc as a Position.Close or Account.Flatten(new[] { Instrument }); would halt it etc

Will watch

**Comment by MicroTrendsTom** [comment]
BTW here is a new one:
 CancelOrdersIfExists(OrdersActive);

**Comment by jmscraig** [comment]
Is that in the commit from a few hours back?

**Comment by MicroTrendsTom** [comment]
> Is that in the commit from a few hours back?
a few before

**Comment by MicroTrendsTom** [comment]
in the error flow we will get reset messages and popups
 if (connectionStatusOrder != ConnectionStatus.Connected).....

**Comment by jmscraig** [comment]
What about bumping up the retry alarm, Timeout, Reset numbers a little?

**Comment by MicroTrendsTom** [comment]
Error workflows are usually kicked off by:
OverFiledOrderDetect
OrderRejection
StrategyTradeWorkFlowState. GoLongValidationRejected
StrategyTradeWorkFlowState. GoShortValidationRejected

definetly good idea to try increase the intervals and timeout/alarms etc
mayeb the default is too fast

**Comment by jmscraig** [comment]
test ConDict ?

**Comment by MicroTrendsTom** [comment]
> What about bumping up the retry alarm, Timeout, Reset numbers a little?
sometimes this collaboration is like playing a Jazz improv - when you understanding is immediate and others would take years haha

**Comment by jmscraig** [comment]
Cool!

**Comment by MicroTrendsTom** [comment]
> test ConDict ?
thats new today a few hours back and is only implemented sparsely with the mode on  IsOrdeActiveConcDict

**Comment by jmscraig** [comment]
Test ConDict or not yet?

**Comment by MicroTrendsTom** [comment]
> Cool!
serious we walk a lonely path ha

**Comment by MicroTrendsTom** [comment]
> Test ConDict or not yet?

yeah i did do a short test and it worked ok on the small sample its ready to test out

**Comment by jmscraig** [comment]
Will do

**Comment by MicroTrendsTom** [comment]
awesome

**Comment by jmscraig** [comment]
One client testing ConDict and one not.  

FYI.  On launch of both hundreds of this log entry.

I think (maybe not) when launching this one. 

![image](https://user-images.githubusercontent.com/15313578/101670709-1f615d00-3a19-11eb-80e0-8a1b2066a2d8.png)


![image](https://user-images.githubusercontent.com/15313578/101670447-c8f41e80-3a18-11eb-9e43-457fe157b27b.png)

**Comment by jmscraig** [comment]
But both clients were running fine very soon

**Comment by jmscraig** [comment]
Using those settings above I launched it on a 12 tick of the MNQ to push it to see where the pressure points are..  

not long and the first on error file popped up.. 

![image](https://user-images.githubusercontent.com/15313578/101671679-6e5bc200-3a1a-11eb-965c-6cb65e7937ad.png)

**Comment by MicroTrendsTom** [comment]
yup good stuff -https://www.screencast.com/t/9650NVSXEork
i need to delete this in a bit but this is it powering several layers due for adding to this project in a more enlightened format

**Comment by MicroTrendsTom** [comment]
> One client testing ConDict and one not.
> 
> FYI. On launch of both hundreds of this log entry.
> 
> I think (maybe not) when launching this one.
> 
> ![image](https://user-images.githubusercontent.com/15313578/101670709-1f615d00-3a19-11eb-80e0-8a1b2066a2d8.png)
> 
> ![image](https://user-images.githubusercontent.com/15313578/101670447-c8f41e80-3a18-11eb-9e43-457fe157b27b.png)
ok please raise new  bug for Print() method  so you get notified of fixes etc

**Comment by jmscraig** [comment]
> yup good stuff -https://www.screencast.com/t/9650NVSXEork
> i need to delete this in a bit but this is it powering several layers due for adding to this project in a more enlightened format

Looks great.. it is whipping along

**Comment by MicroTrendsTom** [comment]
https://github.com/MicroTrendsLtd/NinjaTrader8/issues/33#issue-760587951

**Comment by jmscraig** [comment]
Client testing MACross and ConDict on 1 second  .. is still running fine

![image](https://user-images.githubusercontent.com/15313578/101676797-491e8200-3a21-11eb-9896-b713c49690e5.png)

**Comment by jmscraig** [comment]
Follow up or Close this issue however you want..  Starting a new one with a new topic

**Comment by MicroTrendsTom** [comment]
ok ty
