### ISSUE TITLE
Print Method Exception Bug

### ISSUE THREAD

**Issue by MicroTrendsTom** [MicroTrendsLtd/NinjaTrader8#33]
Print Method Exception Bug
> One client testing ConDict and one not.
> FYI. On launch of both hundreds of this log entry.
> I think (maybe not) when launching this one.
> ![image](https://user-images.githubusercontent.com/15313578/101670709-1f615d00-3a19-11eb-80e0-8a1b2066a2d8.png)
> ![image](https://user-images.githubusercontent.com/15313578/101670447-c8f41e80-3a18-11eb-9e43-457fe157b27b.png)

did you manage to get an output window of it etc?  or in trace?

**Comment by jmscraig** [comment]
see no sign of error in the earliest trace file at launch


![image](https://user-images.githubusercontent.com/15313578/101675831-ee385b00-3a1f-11eb-96c5-77ed5e81ffd9.png)

**Comment by MicroTrendsTom** [comment]
Also unable to reproduce -  will close for now and we can re-open on inspect Print looked ok
