### ISSUE TITLE
2020-12-10 Test Report - Best yet - doubling the workflow timing Did it!

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#36]
Good results.   
Ran all night and through the open on a 10 tick NQ chart.  
Thus far think reliability issues that have plagued me for a week are quite significantly improved.  

Yesterday had 183 Unable to verify errors after the open.  Today only 2.

You can flip it on like a switch.  Tighten up the timing and during volume spikes the error rate climbs quickly.

![image](https://user-images.githubusercontent.com/15313578/101789748-45ddd180-3ac7-11eb-9bba-ac59c560c286.png)

As far as I can tell key thus far doubling 100 to 200 ms and then ( 3 to 6 and 3 to 4) both ran much much better on the short tick chart.

I am not sure what the exact correct config is but it is great to feel be beyond this roadblock.

**Comment by jmscraig** [comment]
Tom just wanted to let you know I wont be around much.   

I need to shut all my focus on non-family things down for the next week.  My son graduates from University this weekend and so it is time for us to celebrate him and that achievement. 

Yea!!

**Comment by MicroTrendsTom** [comment]
> Tom just wanted to let you know I wont be around much.
> 
> I need to shut all my focus on non-family things down for the next week. My son graduates from University this weekend and so it is time for us to celebrate him and that achievement.
> 
> Yea!!
Awesome news congrats to him! and have a nice celebration

**Comment by MicroTrendsTom** [comment]
> Good results.
> Ran all night and through the open on a 10 tick NQ chart.
> Thus far think reliability issues that have plagued me for a week are quite significantly improved.
> 
> Yesterday had 183 Unable to verify errors after the open. Today only 2.
> 
> You can flip it on like a switch. Tighten up the timing and during volume spikes the error rate climbs quickly.
> 
> ![image](https://user-images.githubusercontent.com/15313578/101789748-45ddd180-3ac7-11eb-9bba-ac59c560c286.png)
> 
> As far as I can tell key thus far doubling 100 to 200 ms and then ( 3 to 6 and 3 to 4) both ran much much better on the short tick chart.
> 
> I am not sure what the exact correct config is but it is great to feel be beyond this roadblock.

A Team effort - ty for your collaboration as a result it has grown from a quick solution to something really quite credible and polished you are etched into the hall of frame forever

**Comment by MicroTrendsTom** [comment]
i think looser defaults and a market data lag detector  or order lag detector - to stop compounding issues that result in a jam uip perhaps that trigger the safety mech
