### ISSUE TITLE
Using build at close of commit 2df5771 no longer can disable Trace Logging to Output Window

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#37]
In the build pulled down an hour ago, committed 5 hours ago https://github.com/MicroTrendsLtd/NinjaTrader8/commit/2df5771f74c2754c39b5214880395ca146c414cf

The flipping bools in the properties UI to turn off tracing outputs to the Output Window no longer disables Logging to Tab1 or Tab2.

![image](https://user-images.githubusercontent.com/15313578/101793779-c7cff980-3acb-11eb-9dcb-ecfb8146dcc9.png)

**Comment by MicroTrendsTom** [comment]
ok the public param is : Debug Is Simple Mode

Brain dead now... haha will come back to this one
even just hard code a return

**Comment by MicroTrendsTom** [comment]
cant repro this all looks to be working ok
Will re-open if it comes back on a report etc
