### ISSUE TITLE
Wrong order size for stoploss/profittarget in replay mode

### ISSUE THREAD

**Issue by Sidlercom** [MicroTrendsLtd/NinjaTrader8#42]
in replay/playback mode, stoploss and profittarget are not calculated correctly, and are usually not the same size as the entry order size. In live sim mode everything seems to be correct

**Comment by MicroTrendsTom** [comment]
The samples are provided only to show how to code with the engine.
In the samples the position is hard coded to 4 and the exits are hard coded to 4 in the basic samples
I can't see why replay mode would change any of that -  as it is hard coded.
If there were anomalies under fast play back the samples do not attempt to navigate or fix that.

The engine does not change any of this in commercial applications using the engine under replay and in testing of the samples prior


Sot here would need to be steps to reproduce
Logs, trace, Dataseries, days back and all the settings in play screenshots etc

**Comment by Sidlercom** [comment]
I hope this helps

[NinjaScript Ausgabe 27.01.2021 13_28.txt](https://github.com/MicroTrendsLtd/NinjaTrader8/files/5880190/NinjaScript.Ausgabe.27.01.2021.13_28.txt)

![Screenshot_4](https://user-images.githubusercontent.com/62642679/105991919-adb2a080-60a4-11eb-819f-9fa012c02a66.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/62642679/105992131-0124ee80-60a5-11eb-9901-ccbd3af9bfcd.jpg)

**Comment by admintiger** [comment]
@MicroTrendsTom I can confirm that the wrong order sizes for stop-loss & profit-targets are submitted exactly as reported by @Sidlercom.  It is not a fast market anomaly.  It happens exactly the same regardless of market price rate-of-change or market replay speed.  Even though those order sizes do seem to be hard-coded to 4 contracts, orders totaling 8 contracts each are submitted.

**Comment by MicroTrendsTom** [comment]
ok ty will have to investigate this and resolve

**Comment by admintiger** [comment]
ES 03-21 8-Renko initially. However, the same thing happens with any instrument, bar-type or time series. It will be easy to reproduce the problem.

**Comment by MicroTrendsTom** [comment]
![image](https://user-images.githubusercontent.com/24366913/108853632-f3d02680-75b4-11eb-82ad-6e784f0df07f.png)
removed a double call to place stoploss by means of workflow change
