### ISSUE TITLE
Limit Entry Orders

### ISSUE THREAD

**Issue by admintiger** [MicroTrendsLtd/NinjaTrader8#46]
It doesn't appear that limit entry orders are supported.  Is that true?

**Comment by MicroTrendsTom** [comment]
You can add whatever orders you want in your derived code base
The next layer on top would define different entry types and exits but not here as it would limit its usage 
in time i will add a generic entry exit trade manager at a level above  but for now its as it is -  so you would modify the samples to use limit entrys for example
