### ISSUE TITLE
Stop Order Duplication in Real-Time Trading

### ISSUE THREAD

**Issue by admintiger** [MicroTrendsLtd/NinjaTrader8#47]
This has worked very well during extensive Market Replay testing, but there is a stop-order duplication issue with real-time trading.  At real-time entry four Qty 1 profit-target orders and a single Qty 4 stop are submitted correctly.  However, when the market price moves profitably over time enough to move the stop, instead of moving, a second Qty 4 stop is submitted at the new price and the original Qty 4 stop remains as it was, so there are now Qty 8 stops against a Qty 4 position.  If the market price moves enough to fill the first profit target order, the quantities of both stops change to 3, resulting in Qty 6 stops against a Qty 3 position, and likewise as targets 2 & 3 fill.  However, if the 4th profit target fills, both the correct and duplicate stop orders are cancelled.

**Comment by admintiger** [comment]
Since the post above there have been many instances during real-time trading where duplicate stop orders were also submitted at initial entry.

**Comment by MicroTrendsTom** [comment]
Please can you provide some details
What system /sample is in use  -custom code or other?
What instrument and data series

Brokerage connection and account details sim or other

Please can you provide details screenshots and logs and debug info?
+ any Steps to reproduce the issue etc

**Comment by MicroTrendsTom** [comment]
All testing and other user reports are ok with the provided engine and samples
Based on a no response to the above we will assume this was custom code issues and the matter is rectified and close the ticket
If you do however can supply the above info we can reconsider
many thanks

Tom
