### ISSUE TITLE
Second of Three Issues - Conflicts Concurrent Access to Lists 

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#5]
Greetings!
Happy Monday.
I have 20+ of hours test execution completed against the latest code posted here using my development environment overnight processing with live market date on a Sim account on a VPS during high volume daytime hours.

Completed thousands of successful trade executions but surfaced three issues.

1) Deadlocks
2) LIST<> read write index related conflicts,
3) ChangeOrder submission rejects because the order is in “Cancel Pending” status

Update: I have no control of the bold .. I would not have bolded this text

All three issues have something to do with the quick strategy sample you provided that was based on the NT SampleMACrossover.cs.
So before spending time debugging and writing potential fix code …. Given that ATSSampleMACrossOver  was just a quick sample strategy I wanted to find out if you already have fixes in mind for these issue that are a nice fit with your overall design and principles.
==========================================================

**### The Second Issue is around Conflicts with Concurrent Access to Lists.**  

The Fix:  I think just implementing fine grain, very small in scope (so fast), unique locks per List will go a long way toward solving issues here.  

1) Given the lack of complexity around the edits of the Lists my personal bias is to Limit all edits of a specific list to single function and let everyone else call that function for edits.    

**2) One thing I would try to do for sure**  ... Given the importance and impactfulness to the whole of 'switch (tradeWorkFlow)' in ProcessWorkFlow() I would is try to remove from 'switch(tradeWorkFlow)' dependencies of successful real-time calls against Lists indexes.  

3) From a code simplicity and flexibility standpoint an alternative might be to migrate from using lists to using a ConcurrentDictionary, reported as being about the same performance as a best case implementation of ReaderWriterLockSlim but simpler.  

A few examples:

**Example A.**
`
protected StrategyTradeWorkFlowState ProcessWorkFlow(..)
switch(tradeWorkFlow)

case StrategyTradeWorkFlowState.GoLong:
	OrdersActive.Contains(orderEntry)

case StrategyTradeWorkFlowState.GoShort:
	OrdersActive.Contains(orderEntry)

case StrategyTradeWorkFlowState.GoOCOLongShort:
	OrdersActive.Contains(orderEntry)
`
For these dependencies above my bias would be to either: 
1) try and eliminate the real-time '.Contains(orderEntry)' dependency via proactive preprocessing 
or 2) include OrdersActive.Contains(orderEntry) in a tiny try-catch just above 'switch(tradeWorkFlow)' and add your retry-alarm pattern around use of TradeWorkFlowOnMarketDataEnable(); as the content in the catch { } if the call to OrdersActive.Contains(orderEntry)  was not successful. 

**Example B.**
`
protected StrategyTradeWorkFlowState ProcessWorkFlow(..)
             switch (tradeWorkFlow)
            {
	    case StrategyTradeWorkFlowState.Error:
			    OrdersActive.Clear();
                            ordersStopLoss.Clear();
                            ordersProfitTarget.Clear();
	    } 	

`
This one feels prone to be now or someday a potential source of deadlocks.  
Personally I might just 
1) Set a string process flow variable or a dedicated local bool created at the top of ProcessWorkFlow() and just flip that flag in StrategyTradeWorkFlowState.Error: 
2) Actually make the calls just below ( maybe just above 'switch(tradeWorkFlow) if not yet complete) in a in a tiny try-catch  and add your retry-alarm pattern around use of TradeWorkFlowOnMarketDataEnable(); as the content in the catch { } if the '.Clear() calls were not successful.
 

**Example C.**  
`
public void Print(string msg)
	+ "|AO=" + OrdersActive.Count.ToString()

`

Access to List.Count rarely fails.  This is pretty low risk so personally I might just add a try-catch around the message construct and call this one done. 

**Example D**
`
public void CancelAllOrders()
	OrdersActive.Clear();

private void SubmitStopLossInternal()
	StopLossOrders.Clear();
private void SubmitProfitTargetInternal()
	ProfitTargetOrders.Clear();

`
Each of the functions above is pretty small.  For these I am personally biased to first maybe try the fine grain lock-per-List and no other changes.  If needed migrate to function or functions dedicated to all edits of lists. 

**Your Thoughts?  Existing Code solutions to paste in?  Better Ideas?**
James

**Comment by jmscraig** [comment]
I am spinning up a proposed Pull Request to get something done to reduce the list index exception issues hopefully a reduction of deadlocks.  This Pull Request will include ideas from Fix #1 above but does not incorporate any concepts in support of potential Fixes labeled #1, #2 or #3 above.


What I will include: 

"The Fix: I think just implementing fine grain, very small in scope (so fast), unique locks per List will go a long way toward solving issues here."

**Comment by MicroTrendsTom** [comment]
yes that makes sense - fine grain -
" list index exception issues"    i would like to replicate this and see it also first hand to understand where that came from etc within context of settings and test type etc

**Comment by MicroTrendsTom** [comment]
ConcurrentDictionary.... also sounds like a great idea

**Comment by MicroTrendsTom** [comment]
i will wait for your idea on the solution to avoid updating that area etc

**Comment by MicroTrendsTom** [comment]
ok i was late...did see the pull request :-)

**Comment by MicroTrendsTom** [comment]
looks to be fixed with fine grain locks on the lists in all code instances
