### ISSUE TITLE
Regarding the latest build. Did you intend to include Resource.resx and @SMA.cs ?

### ISSUE THREAD

**Issue by jmscraig** [MicroTrendsLtd/NinjaTrader8#56]
Hi Tom, 

Errors on the build for missing components.

Regarding the latest build. Did you intend to include Resource.resx and @SMA.cs ?

bin\Custom\Resource.resx
bin\Custom\Indicators\binCustomIndicators.cs

Example source of error
`
Ln377        
[Display(ResourceType = typeof(**Custom.Resource**), 
      Name = "SignalType1", Description = "0:off, 1:Double MA Crossover",  

![Missings](https://user-images.githubusercontent.com/15313578/154771128-79d3a101-b5f6-4bed-9eb8-f5a736609817.JPG)

I could have slid the @SMA.cs in but was not completely sure on what you had included in Resource.resx

James

**Comment by MicroTrendsTom** [comment]
dam so fiddly with  github...  in TFS i can chose mappings based on subfolders and so on.
GitHub wants to map from main outwards. i think...

So what to do...?
1)Create a new repos and structure it so its easy to get and map to local NinjaTrader 8 folders
2) or is there some way to branch and do it that way..


E.G how to map to from here:
https://github.com/MicroTrendsLtd/NinjaTrader8/tree/main/ATSQuadroStrategyBase/NinjaTrader%208

to here \documents\NinjaTrader 8
NinjaTrader 8 
![image](https://user-images.githubusercontent.com/24366913/154789396-0c97ffcd-4862-48e5-86c3-d86c2b3009e3.png)

guess i screwed up the structure at the start ooops

**Comment by jmscraig** [comment]
1) "use the NinjaTrader Custom Project"  .. the challenge is that now you have to manage conflicts and merge your changes in with existing customizations in the NinjaTrader.Custom.csproj and the Resource.resx file.  

2) In a Github repo the two simplest approach from an integration to local NT8 standpoint would be to:
1) limit all custom development work to what NT8's Import / Export of Zip files processes can handle
2) Create a NT8 import format zip file with of the custom elements 
3) Add that Zip to your repo with the source.. just like we might add a pdb file.  
4) Use the NT8 import or manually copy the files in by hand.. just as normal.  

3) On the other hand, as long as limit your local language needs to the default NT8 of English  I actually did not find it too hard to map required references to stand alone projects.   The best example I have seen of creating standalone compilable NT8 projects can be seen on Gitlab which is similar to GitHub.   https://gitlab.com/jasonnatordaytrader/jdt.nt8

**Comment by jmscraig** [comment]
So that I can take a look at the code as posted in the repository yesterday..  If your ../bin/Custom/Resource.resx file shows recent modifications would you mind adding it to the repository or posting it here?

**Comment by MicroTrendsTom** [comment]
> 
Note: For use just get the code and copy it to the NT8  folders and use the NT Custom project - copy over the top i spent many hours github cant do it. get the zip or clone and copy over is easiest.  as shown here

![image](https://user-images.githubusercontent.com/24366913/154848813-774fd0d0-f566-49a9-8413-d65bd706b5ca.png)

**Comment by MicroTrendsTom** [comment]
1)  get the code from GitHub. Clone or Code Zip file
2) copy the code within NinjaTrader 8 to the local documents NinjaTrader 8 folders
3) Start NT8 - compile within the NT8 Code Editor
4) For Visual Studio open from the code editor or  double click the NinjaTrader.Custom.csProj
![image](https://user-images.githubusercontent.com/24366913/154849272-2e63c414-86a1-4308-97af-6af5ad542eda.png)

**Comment by MicroTrendsTom** [comment]
Please see #61 
Also might fix this issue anyway will check it out ty  - but for sure use the system as detailed in  #61

**Comment by MicroTrendsTom** [comment]
> 
The system is a framework which merges into the NT8 custom project it is not meant to be a standalone project all we would do is be duplicating  and adding all the code in from NT8 this is the easiest way to work with with it:   Just install it over the top of NT8 and then you can access all your 3rd party stuff and the NT8 source etc
https://github.com/MicroTrendsLtd/NinjaTrader8/discussions/61#discussion-3889698

**Comment by MicroTrendsTom** [comment]
Note: The prior releases in the NT forums do use a NT Zip file approach for easy import  
So this will be need to be made again and probably best to have that here somewhere with a link etc
That will be easiest indeed for the new releases will make an issue for that... and close this down as the project you opened is redundant etc.

**Comment by jmscraig** [comment]
Hi Tom, 

Thanks for the Step by Step notes.  That is the same process I used to try load and play with the Hybrid Strategy yesterday.    I people will find the notes helpful.  

The only really tricky part during my first attempts at compiling was the dependency on Resource.resx and not knowing if you had customized it.  You have not mentioned Resources.resx in the thread and Hybrid seems to work fine using my existing Resources.rexs so I conclude that there is no dependency unique to your local copy.  

The one hitch I saw after just copying the files into my existing NT8 structure was during compile the NT8 embedded compiler was unable to resolve references for "Custom.Resource".   I after looking at things I just deleted the characters " Custom. " and everything compiled fine. 


Again, the UI panel is fantastic.
James

**Comment by MicroTrendsTom** [comment]
hopefully the zip export and import will resolve issues thanks for the feedback,. glad you like hybrid trading approach :-)

**Comment by jmscraig** [comment]
Yes I personally don't need that and very rarely use the actual NT8 Zip import tool because I review all the code before I add it to my carefully managed collection.  

I really brought it up to possibly use as a handy rubric, a model or pattern to follow to make it easier to know what people will find easy and uncomplicated to install into their existing environments.

**Comment by jmscraig** [comment]
Yes I do like the panel.. I have worked on use of a large grid of smaller buttons in the upper left corner of the chart to do the same thing as your panel and I concluded that many buttons on the chart was neve going to be a good approach.

Replacing the right panel in whole so cleanly is fantastic.   Any even my strategies that run fully automatically by default I leave buttons up to adjust stops to better resistance points and I my human 'bias' from natural to bull or bear when I see market events outside the norms the algo was targeted to address.  

So in small ways or large Hybrid is my default approach..  

Looks like we are off on a fantastic journey here..

**Comment by jmscraig** [comment]
Today I will spend more time with the Hybrid Strategy loaded panel and thinking about how I might first be able to use them

**Comment by MicroTrendsTom** [comment]
> 
NT Zip yes as detailed in the first releases and  NT Forum etc we did use this method and now it fails so we can no longer use that method

**Comment by MicroTrendsTom** [comment]
> 
skies the limit....  you can see how we use it for the NYSE gap and session breakout mode  in the trading group  9.15 EST live screenshare and voice commentary every day etc

This issue is closed we can discuss details in the open discussion or best trading room for education and techniques etc
