### ISSUE TITLE
Which code to compile

### ISSUE THREAD

**Issue by FuriousMangouste** [MicroTrendsLtd/NinjaTrader8#69]
Hi,

Installation guide is lacking for step 3 :

"Start NT8 - open the NT8 Code Editor and compile the code"
**OK, but which code ?*
![nt_supp](https://user-images.githubusercontent.com/60436348/176995893-c5211422-ef82-4fcb-b1c2-01207842cf09.png)
*

I tried to over "Strategies" and Compile the full thing , I then added the references when I got the error message so I assume I compiled the right thing ?
But the Order GUI isn't like on your screenshots. I still have the old GUI.

SO im' wondering if I need anything more to do ? 

Thanks for your help.

**Comment by MicroTrendsTom** [comment]
This is for developers with a good experience of coding with NT8 etc so there is likely some details left out :-)

-  Make sure you got the latest code base direct from GitHub
-  Installation: https://github.com/MicroTrendsLtd/NinjaTrader8/discussions/61

 NT8 Code Editor Setup: https://github.com/MicroTrendsLtd/NinjaTrader8/discussions/65
 - Yes add the assemblies shown etc
 - Hit F5 to compile code there is only one set of code "all of it" is compiled.
>>>If no errors messages all good

use an installed sample with the GUI to see it
https://github.com/MicroTrendsLtd/NinjaTrader8/tree/main/ATSQuadroStrategyBase/NinjaTrader%208/bin/Custom/Strategies
ATSSamplePriceReversalTestHybridAlgo.cs

**Comment by FuriousMangouste** [comment]
Thanks for the prompt reply.

Pretty new to NT8 indeed. 
So everything was well compiled (no error message and "ok" sound)

I selected the TestHybridAlgo and checked the TradeManger but GUI is still standard one. AM I still missing something ?
![nt_supppo](https://user-images.githubusercontent.com/60436348/177039836-3e0b6585-7071-410e-95a0-956205621f23.png)

Sorry to bother you with basics questions. 
I was interest by the trade manager and wanted to dig a bit into what you created :)
