### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by R1zzler** [MicroTrendsLtd/NinjaTrader8#90]
I am having the following error:
![AST error](https://user-images.githubusercontent.com/105330680/214772717-487b250f-0388-4507-b988-16dc33e3b728.jpg)

**Comment by MicroTrendsTom** [comment]
This is a duplicate and a basic RTFM error.
Read here:  https://github.com/MicroTrendsLtd/NinjaTrader8
Note: Get the latest code
