### ISSUE TITLE
Compilation Error With Base

### ISSUE THREAD

**Issue by Entwaze** [MicroTrendsLtd/NinjaTrader8#98]
Im having a compilation error with the files
image
ATSQuadroBaseStrategyPropertyGridPopUp\xaml.cs - the type or namespcae name wpfPropertyGrid does not exist in the namespace
ATSQuadroBaseStrategyPropertyGridPopUp\xaml.cs - the type or namespcae name PropertyGrid does not exist in the namespace
Looks to be missing these two Property grid files potentially?
I just copy and pasted over a couple of time because i am really interested in programming over the GUI and advanced coding if theres any way you could help or reupload a Ninja .zip addOn that would be super sweet!
Post a comment below if anyone else has had same issue

**Comment by Entwaze** [comment]
Im having a compilation error with the files
![image](https://user-images.githubusercontent.com/90291948/216351296-2b8e855d-6698-456f-9f4c-f762bad29251.png)
ATSQuadroBaseStrategyPropertyGridPopUp\xaml.cs - the type or namespcae name wpfPropertyGrid does not exist in the namespace
ATSQuadroBaseStrategyPropertyGridPopUp\xaml.cs - the type or namespcae name PropertyGrid does not exist in the namespace
Looks to be missing these two Property grid files potentially?
I just copy and pasted over a couple of time because i am really interested in programming over the GUI and advanced coding if theres any way you could help or reupload a Ninja .zip addOn that would be super sweet!
Post a comment below if anyone else has had same issue

**Comment by MicroTrendsTom** [comment]
Please read the whole read me and follow the exact steps to install and setup post install:
Get the latest Zip file from the Front page  > Code button
https://github.com/MicroTrendsLtd/NinjaTrader8
